FROM docker.io/redhat/ubi9
ARG  BUILDOS
ENV  url=google.com BUILDOS=linux
RUN  echo "Hi Chanu from -" $BUILDOS

## Key obeservation when I pass same varibale as env also and I want to change it at runtime it will take only env value